#ifndef FVV_SEMANTIC_H
#define FVV_SEMANTIC_H

// Bit size type
#define FVV_BIT_VARIABLE                                          0x00

// Descriptors type
#define FVV_DESCRIPTOR_B                                          0x00
#define FVV_DESCRIPTOR_F                                          0x01
#define FVV_DESCRIPTOR_FL                                         0x02
#define FVV_DESCRIPTOR_I                                          0x03
#define FVV_DESCRIPTOR_SE                                         0x04
#define FVV_DESCRIPTOR_ST                                         0x05
#define FVV_DESCRIPTOR_U                                          0x06
#define FVV_DESCRIPTOR_UE                                         0x07

// Bit size
#define FVV_BIT_TRAILING_ZERO_8BITS                               8
#define FVV_BIT_VUH_UNIT_TYPE                                     5
#define FVV_BIT_VUH_V3C_PARAMETER_SET_ID                          4
#define FVV_BIT_VUH_ATLAS_ID                                      6
#define FVV_BIT_VUH_ATTRIBUTE_INDEX                               7
#define FVV_BIT_VUH_ATTRIBUTE_PARTITION_INDEX                     5
#define FVV_BIT_VUH_MAP_INDEX                                     4
#define FVV_BIT_VUH_AUXILIARY_VIDEO_FLAG                          1
#define FVV_BIT_VUH_RESERVED_ZERO_12BITS                          12
#define FVV_BIT_VUH_RESERVED_ZERO_17BITS                          17
#define FVV_BIT_VUH_RESERVED_ZERO_27BITS                          27
#define FVV_BIT_ALIGNMENT_BIT_EQUAL_TO_ONE                        1
#define FVV_BIT_ALIGNMENT_BIT_EQUAL_TO_ZERO                       1
#define FVV_BIT_VPS_V3C_PARAMETER_SET_ID                          4
#define FVV_BIT_VPS_RESERVED_ZERO_8BITS                           8
#define FVV_BIT_VPS_ATLAS_COUNT_MINUS1                            6
#define FVV_BIT_VPS_ATLAS_ID                                      6
#define FVV_BIT_VPS_FRAME_WIDTH                                   FVV_BIT_VARIABLE
#define FVV_BIT_VPS_FRAME_HEIGHT                                  FVV_BIT_VARIABLE
#define FVV_BIT_VPS_MAP_COUNT_MINUS1                              4
#define FVV_BIT_VPS_MULTIPLE_MAP_STREAMS_PRESENT_FLAG             1
#define FVV_BIT_VPS_MAP_ABSOLUTE_CODING_ENABLED_FLAG              1
#define FVV_BIT_VPS_MAP_PREDICTOR_INDEX_DIFF                      FVV_BIT_VARIABLE
#define FVV_BIT_VPS_AUXILIARY_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_OCCUPANCY_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_GEOMETRY_VIDEO_PRESENT_FLAG                   1
#define FVV_BIT_VPS_ATTRIBUTE_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_EXTENSION_PRESENT_FLAG                        1
#define FVV_BIT_VPS_EXTENSION_8BITS                               8
#define FVV_BIT_VPS_EXTENSION_LENGTH_MINUS1                       FVV_BIT_VARIABLE
#define FVV_BIT_VPS_EXTENSION_DATA_BYTE                           8
#define FVV_BIT_PTL_TIER_FLAG                                     1
#define FVV_BIT_PTL_PROFILE_CODEC_GROUP_IDC                       7
#define FVV_BIT_PTL_PROFILE_TOOLSET_IDC                           8
#define FVV_BIT_PTL_PROFILE_RECONSTRUCTION_IDC                    8
#define FVV_BIT_PTL_RESERVED_ZERO_16BITS                          16
#define FVV_BIT_PTL_RESERVED_0XFFFF_16BITS                        16
#define FVV_BIT_PTL_LEVEL_IDC                                     8
#define FVV_BIT_PTL_NUM_SUB_PROFILES                              6
#define FVV_BIT_PTL_EXTENDED_SUB_PROFILE_FLAG                     1
#define FVV_BIT_PTL_SUB_PROFILE_IDC                               FVV_BIT_VARIABLE
#define FVV_BIT_PTL_TOOL_CONSTRAINTS_PRESENT_FLAG                 1
#define FVV_BIT_SSNH_UNIT_SIZE_PRECISION_BYTES_MINUS1             3
#define FVV_BIT_SSNH_RESERVED_ZERO_5BITS                          5
#define FVV_BIT_SSNU_NAL_UNIT_SIZE                                FVV_BIT_VARIABLE
#define FVV_BIT_OI_OCCUPANCY_CODEC_ID                             8
#define FVV_BIT_OI_LOSSY_OCCUPANCY_COMPRESSION_THRESHOLD          8
#define FVV_BIT_OI_OCCUPANCY_2D_BIT_DEPTH_MINUS1                  5
#define FVV_BIT_OI_OCCUPANCY_MSB_ALIGN_FLAG                       1
#define FVV_BIT_GI_GEOMETRY_CODEC_ID                              8
#define FVV_BIT_GI_GEOMETRY_2D_BIT_DEPTH_MINUS1                   5
#define FVV_BIT_GI_GEOMETRY_MSB_ALIGN_FLAG                        1
#define FVV_BIT_GI_GEOMETRY_3D_COORDINATES_BIT_DEPTH_MINUS1       5
#define FVV_BIT_GI_AUXILIARY_GEOMETRY_CODEC_ID                    8
#define FVV_BIT_AI_ATTRIBUTE_COUNT                                7
#define FVV_BIT_AI_ATTRIBUTE_TYPE_ID                              4
#define FVV_BIT_AI_ATTRIBUTE_CODEC_ID                             8
#define FVV_BIT_AI_AUXILIARY_ATTRIBUTE_CODEC_ID                   8
#define FVV_BIT_AI_ATTRIBUTE_MAP_ABSOLUTE_CODING_PERSISTENCE_FLAG 1
#define FVV_BIT_AI_ATTRIBUTE_DIMENSION_MINUS1                     6
#define FVV_BIT_AI_ATTRIBUTE_DIMENSION_PARTITIONS_MINUS1          6
#define FVV_BIT_AI_ATTRIBUTE_PARTITION_CHANNELS_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AI_ATTRIBUTE_2D_BIT_DEPTH_MINUS1                 5
#define FVV_BIT_AI_ATTRIBUTE_MSB_ALIGN_FLAG                      1
#define FVV_BIT_PTC_ONE_V3C_FRAME_ONLY_FLAG                      1
#define FVV_BIT_PTC_EOM_CONSTRAINT_FLAG                          1
#define FVV_BIT_PTC_MAX_MAP_COUNT_MINUS1                         4
#define FVV_BIT_PTC_MAX_ATLAS_COUNT_MINUS1                       4
#define FVV_BIT_PTC_MULTIPLE_MAP_STREAMS_CONSTRAINT_FLAG         1
#define FVV_BIT_PTC_PLR_CONSTRAINT_FLAG                          1
#define FVV_BIT_PTC_ATTRIBUTE_MAX_DIMENSION_MINUS1               6
#define FVV_BIT_PTC_ATTRIBUTE_MAX_DIMENSION_PARTITIONS_MINUS1    6
#define FVV_BIT_PTC_NO_EIGHT_ORIENTATIONS_CONSTRAINT_FLAG        1
#define FVV_BIT_PTC_NO_45DEGREE_PROJECTION_PATCH_CONSTRAINT_FLAG 1
#define FVV_BIT_PTC_RESERVED_ZERO_6BITS                          6
#define FVV_BIT_PTC_NUM_RESERVED_CONSTRAINT_BYTES                8
#define FVV_BIT_PTC_RESERVED_CONSTRAINT_BYTE                     8
#define FVV_BIT_RBSP_BYTE                                        8
#define FVV_BIT_NAL_FORBIDDEN_ZERO_BIT                           1
#define FVV_BIT_NAL_UNIT_TYPE                                    6
#define FVV_BIT_NAL_LAYER_ID                                     6
#define FVV_BIT_NAL_TEMPORAL_ID_PLUS1                            3
#define FVV_BIT_ASPS_ATLAS_SEQUENCE_PARAMETER_SET_ID             FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_FRAME_WIDTH                                 FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_FRAME_HEIGHT                                FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_GEOMETRY_3D_BIT_DEPTH_MINUS1                5
#define FVV_BIT_ASPS_GEOMETRY_2D_BIT_DEPTH_MINUS1                5
#define FVV_BIT_ASPS_LOG2_MAX_ATLAS_FRAME_ORDER_CNT_LSB_MINUS4 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_MAX_DEC_ATLAS_FRAME_BUFFERING_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_LONG_TERM_REF_ATLAS_FRAMES_FLAG 1
#define FVV_BIT_ASPS_NUM_REF_ATLAS_FRAME_LISTS_IN_ASPS \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_USE_EIGHT_ORIENTATIONS_FLAG                  1
#define FVV_BIT_ASPS_EXTENDED_PROJECTION_ENABLED_FLAG             1
#define FVV_BIT_ASPS_MAX_NUMBER_PROJECTIONS_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_NORMAL_AXIS_LIMITS_QUANTIZATION_ENABLED_FLAG 1
#define FVV_BIT_ASPS_NORMAL_AXIS_MAX_DELTA_VALUE_ENABLED_FLAG     1
#define FVV_BIT_ASPS_PATCH_PRECEDENCE_ORDER_FLAG                  1
#define FVV_BIT_ASPS_LOG2_PATCH_PACKING_BLOCK_SIZE                3
#define FVV_BIT_ASPS_PATCH_SIZE_QUANTIZER_PRESENT_FLAG            1
#define FVV_BIT_ASPS_MAP_COUNT_MINUS1                             4
#define FVV_BIT_ASPS_PIXEL_DEINTERLEAVING_ENABLED_FLAG            1
#define FVV_BIT_ASPS_MAP_PIXEL_DEINTERLEAVING_FLAG                1
#define FVV_BIT_ASPS_RAW_PATCH_ENABLED_FLAG                       1
#define FVV_BIT_ASPS_EOM_PATCH_ENABLED_FLAG                       1
#define FVV_BIT_ASPS_EOM_FIX_BIT_COUNT_MINUS1                     4
#define FVV_BIT_ASPS_AUXILIARY_VIDEO_ENABLED_FLAG                 1
#define FVV_BIT_ASPS_PLR_ENABLED_FLAG                             1
#define FVV_BIT_ASPS_VUI_PARAMETERS_PRESENT_FLAG                  1
#define FVV_BIT_ASPS_EXTENSION_PRESENT_FLAG                       1
#define FVV_BIT_ASPS_VPCC_EXTENSION_PRESENT_FLAG                  1
#define FVV_BIT_ASPS_EXTENSION_7BITS                              7
#define FVV_BIT_ASPS_EXTENSION_DATA_FLAG                          1
#define FVV_BIT_PLRI_MAP_PRESENT_FLAG                             1
#define FVV_BIT_PLRI_NUMBER_OF_MODES_MINUS1                       4
#define FVV_BIT_PLRI_INTERPOLATE_FLAG                             1
#define FVV_BIT_PLRI_FILLING_FLAG                                 1
#define FVV_BIT_PLRI_MINIMUM_DEPTH                                2
#define FVV_BIT_PLRI_NEIGHBOUR_MINUS1                             2
#define FVV_BIT_PLRI_BLOCK_THRESHOLD_PER_PATCH_MINUS1             6
#define FVV_BIT_AFPS_ATLAS_FRAME_PARAMETER_SET_ID                 FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_ATLAS_SEQUENCE_PARAMETER_SET_ID              FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_OUTPUT_FLAG_PRESENT_FLAG                     1
#define FVV_BIT_AFPS_NUM_REF_IDX_DEFAULT_ACTIVE_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_ADDITIONAL_LT_AFOC_LSB_LEN                 FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_LOD_MODE_ENABLED_FLAG                      1
#define FVV_BIT_AFPS_RAW_3D_OFFSET_BIT_COUNT_EXPLICIT_MODE_FLAG 1
#define FVV_BIT_AFPS_EXTENSION_PRESENT_FLAG                     1
#define FVV_BIT_AFPS_EXTENSION_8BITS                            8
#define FVV_BIT_AFPS_EXTENSION_DATA_FLAG                        1
#define FVV_BIT_AFTI_SINGLE_TILE_IN_ATLAS_FRAME_FLAG            1
#define FVV_BIT_AFTI_UNIFORM_PARTITION_SPACING_FLAG             1
#define FVV_BIT_AFTI_PARTITION_COLS_WIDTH_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_ROWS_HEIGHT_MINUS1               FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_NUM_PARTITION_COLUMNS_MINUS1               FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_NUM_PARTITION_ROWS_MINUS1                  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_COLUMN_WIDTH_MINUS1              FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_ROW_HEIGHT_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_SINGLE_PARTITION_PER_TILE_FLAG             1
#define FVV_BIT_AFTI_NUM_TILES_IN_ATLAS_FRAME_MINUS1            FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_TOP_LEFT_PARTITION_IDX                     FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_BOTTOM_RIGHT_PARTITION_COLUMN_OFFSET \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_BOTTOM_RIGHT_PARTITION_ROW_OFFSET \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_AUXILIARY_VIDEO_TILE_ROW_WIDTH_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_AUXILIARY_VIDEO_TILE_ROW_HEIGHT FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_SIGNALLED_TILE_ID_FLAG          1
#define FVV_BIT_AFTI_SIGNALLED_TILE_ID_LENGTH_MINUS1 FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_TILE_ID                         FVV_BIT_VARIABLE
#define FVV_BIT_AAPS_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_BIT_VARIABLE
#define FVV_BIT_AAPS_EXTENSION_PRESENT_FLAG              1
#define FVV_BIT_AAPS_VPCC_EXTENSION_PRESENT_FLAG         1
#define FVV_BIT_AAPS_EXTENSION_7BITS                     7
#define FVV_BIT_AAPS_EXTENSION_DATA_FLAG                 1
#define FVV_BIT_AFRAME_TYPE                              3
#define FVV_BIT_FF_BYTE                                  8
#define FVV_BIT_RBSP_STOP_ONE_BIT                        1
#define FVV_BIT_RBSP_ALIGNMENT_ZERO_BIT                  1
#define FVV_BIT_ATH_NO_OUTPUT_OF_PRIOR_ATLAS_FRAMES_FLAG 1
#define FVV_BIT_ATH_ATLAS_FRAME_PARAMETER_SET_ID         FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ATLAS_ADAPTATION_PARAMETER_SET_ID    FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ID                                   FVV_BIT_VARIABLE
#define FVV_BIT_ATH_TYPE                                 FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ATLAS_OUTPUT_FLAG                    1
#define FVV_BIT_ATH_ATLAS_FRM_ORDER_CNT_LSB              FVV_BIT_VARIABLE
#define FVV_BIT_ATH_REF_ATLAS_FRAME_LIST_ASPS_FLAG       1
#define FVV_BIT_ATH_REF_ATLAS_FRAME_LIST_IDX             FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ADDITIONAL_AFOC_LSB_PRESENT_FLAG     1
#define FVV_BIT_ATH_ADDITIONAL_AFOC_LSB_VAL              FVV_BIT_VARIABLE
#define FVV_BIT_ATH_POS_MIN_D_QUANTIZER                  5
#define FVV_BIT_ATH_POS_DELTA_MAX_D_QUANTIZER            5
#define FVV_BIT_ATH_PATCH_SIZE_X_INFO_QUANTIZER          3
#define FVV_BIT_ATH_PATCH_SIZE_Y_INFO_QUANTIZER          3
#define FVV_BIT_ATH_RAW_3D_OFFSET_AXIS_BIT_COUNT_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ATH_NUM_REF_IDX_ACTIVE_OVERRIDE_FLAG          1
#define FVV_BIT_ATH_NUM_REF_IDX_ACTIVE_MINUS1                 FVV_BIT_VARIABLE
#define FVV_BIT_NUM_REF_ENTRIES                               FVV_BIT_VARIABLE
#define FVV_BIT_ST_REF_ATLAS_FRAME_FLAG                       1
#define FVV_BIT_ABS_DELTA_AFOC_ST                             FVV_BIT_VARIABLE
#define FVV_BIT_STRAF_ENTRY_SIGN_FLAG                         1
#define FVV_BIT_AFOC_LSB_LT                                   FVV_BIT_VARIABLE
#define FVV_BIT_AAPS_VPCC_CAMERA_PARAMETERS_PRESENT_FLAG      1
#define FVV_BIT_ACP_CAMERA_MODEL                              8
#define FVV_BIT_ACP_SCALE_ENABLED_FLAG                        1
#define FVV_BIT_ACP_OFFSET_ENABLED_FLAG                       1
#define FVV_BIT_ACP_ROTATION_ENABLED_FLAG                     1
#define FVV_BIT_ACP_SCALE_ON_AXIS                             32
#define FVV_BIT_ACP_OFFSET_ON_AXIS                            32
#define FVV_BIT_ACP_ROTATION_QX                               16
#define FVV_BIT_ACP_ROTATION_QY                               16
#define FVV_BIT_ACP_ROTATION_QZ                               16
#define FVV_BIT_ASPS_VPCC_REMOVE_DUPLICATE_POINT_ENABLED_FLAG 1
#define FVV_BIT_ASPS_VPCC_SURFACE_THICKNESS_MINUS1            FVV_BIT_VARIABLE
#define FVV_BIT_ATDU_PATCH_MODE                               FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_REF_INDEX                                FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_OVERRIDE_2D_PARAMS_FLAG                  1
#define FVV_BIT_MPDU_2D_POS_X                                 FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_2D_POS_Y                                 FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_2D_DELTA_SIZE_X                          FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_2D_DELTA_SIZE_Y                          FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_OVERRIDE_3D_PARAMS_FLAG                  1
#define FVV_BIT_MPDU_3D_OFFSET_U                              FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_3D_OFFSET_V                              FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_3D_OFFSET_D                              FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_3D_RANGE_D                               FVV_BIT_VARIABLE
#define FVV_BIT_MPDU_OVERRIDE_PLR_FLAG                        1
#define FVV_BIT_EPDU_PATCH_IN_AUXILIARY_VIDEO_FLAG            1
#define FVV_BIT_EPDU_2D_POS_X                                 FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_2D_POS_Y                                 FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_2D_SIZE_X_MINUS1                         FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_2D_SIZE_Y_MINUS1                         FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_PATCH_COUNT_MINUS1                       FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_ASSOCIATED_PATCH_IDX                     FVV_BIT_VARIABLE
#define FVV_BIT_EPDU_POINTS                                   FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_REF_INDEX                                FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_PATCH_INDEX                              FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_2D_POS_X                                 FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_2D_POS_Y                                 FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_2D_DELTA_SIZE_X                          FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_2D_DELTA_SIZE_Y                          FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_3D_OFFSET_U                              FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_3D_OFFSET_V                              FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_3D_OFFSET_D                              FVV_BIT_VARIABLE
#define FVV_BIT_IPDU_3D_RANGE_D                               FVV_BIT_VARIABLE
#define FVV_BIT_PDU_2D_POS_X                                  FVV_BIT_VARIABLE
#define FVV_BIT_PDU_2D_POS_Y                                  FVV_BIT_VARIABLE
#define FVV_BIT_PDU_2D_SIZE_X_MINUS1                          FVV_BIT_VARIABLE
#define FVV_BIT_PDU_2D_SIZE_Y_MINUS1                          FVV_BIT_VARIABLE
#define FVV_BIT_PDU_LOD_ENABLED_FLAG                          1
#define FVV_BIT_PDU_LOD_SCALE_X_MINUS1                        FVV_BIT_VARIABLE
#define FVV_BIT_PDU_LOD_SCALE_Y_IDC                           FVV_BIT_VARIABLE
#define FVV_BIT_PLRD_LEVEL                                    1
#define FVV_BIT_PLRD_PRESENT_BLOCK_FLAG                       1
#define FVV_BIT_PLRD_PRESENT_FLAG                             1
// TODO: FVV_BIT_PLRD_BLOCK_MODE_MINUS1 is not specified in Draft
#define FVV_BIT_PLRD_BLOCK_MODE_MINUS1                        4
// TODO: FVV_BIT_PLRD_MODE_MINUS1 is not specified in Draft
#define FVV_BIT_PLRD_MODE_MINUS1                              4
#define FVV_BIT_RPDU_PATCH_IN_AUXILIARY_VIDEO_FLAG            1
#define FVV_BIT_RPDU_2D_POS_X                                 FVV_BIT_VARIABLE
#define FVV_BIT_RPDU_2D_POS_Y                                 FVV_BIT_VARIABLE
#define FVV_BIT_RPDU_2D_SIZE_X_MINUS1                         FVV_BIT_VARIABLE
#define FVV_BIT_RPDU_2D_SIZE_Y_MINUS1                         FVV_BIT_VARIABLE
#define FVV_BIT_RPDU_POINTS_MINUS1                            FVV_BIT_VARIABLE
#define FVV_BIT_SM_PAYLOAD_TYPE_BYTE                          8
#define FVV_BIT_SM_PAYLOAD_SIZE_BYTE                          8
// Descriptors

#define FVV_DESCRIPTOR_VUH_UNIT_TYPE                          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_V3C_PARAMETER_SET_ID               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATLAS_ID                           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATTRIBUTE_INDEX                    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATTRIBUTE_PARTITION_INDEX          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_MAP_INDEX                          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_AUXILIARY_VIDEO_FLAG               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_12BITS               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_17BITS               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_27BITS               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ALIGNMENT_BIT_EQUAL_TO_ONE             FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_ALIGNMENT_BIT_EQUAL_TO_ZERO            FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_VPS_V3C_PARAMETER_SET_ID               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_RESERVED_ZERO_8BITS                FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATLAS_COUNT_MINUS1                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATLAS_ID                           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_FRAME_WIDTH                        FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_FRAME_HEIGHT                       FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_MAP_COUNT_MINUS1                   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MULTIPLE_MAP_STREAMS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MAP_ABSOLUTE_CODING_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MAP_PREDICTOR_INDEX_DIFF FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_AUXILIARY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_OCCUPANCY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_GEOMETRY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATTRIBUTE_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_PRESENT_FLAG     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_8BITS            FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_LENGTH_MINUS1    FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_EXTENSION_DATA_BYTE        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_TIER_FLAG                  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_CODEC_GROUP_IDC    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_TOOLSET_IDC        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_RECONSTRUCTION_IDC FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_RESERVED_ZERO_16BITS       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_RESERVED_0XFFFF_16BITS     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_LEVEL_IDC                  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_NUM_SUB_PROFILES           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_EXTENDED_SUB_PROFILE_FLAG  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_SUB_PROFILE_IDC            FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_TOOL_CONSTRAINTS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNH_UNIT_SIZE_PRECISION_BYTES_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNH_RESERVED_ZERO_5BITS FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNU_NAL_UNIT_SIZE       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_LOSSY_OCCUPANCY_COMPRESSION_THRESHOLD \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_CODEC_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_CODEC_ID        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_3D_COORDINATES_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_AUXILIARY_GEOMETRY_CODEC_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_COUNT             FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_TYPE_ID           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_CODEC_ID          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_AUXILIARY_ATTRIBUTE_CODEC_ID \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_MAP_ABSOLUTE_CODING_PERSISTENCE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_DIMENSION_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_DIMENSION_PARTITIONS_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_PARTITION_CHANNELS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ONE_V3C_FRAME_ONLY_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_EOM_CONSTRAINT_FLAG     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MAX_MAP_COUNT_MINUS1    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MAX_ATLAS_COUNT_MINUS1  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MULTIPLE_MAP_STREAMS_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_PLR_CONSTRAINT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ATTRIBUTE_MAX_DIMENSION_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ATTRIBUTE_MAX_DIMENSION_PARTITIONS_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NO_EIGHT_ORIENTATIONS_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NO_45DEGREE_PROJECTION_PATCH_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_RESERVED_ZERO_6BITS FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NUM_RESERVED_CONSTRAINT_BYTES \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_RESERVED_CONSTRAINT_BYTE FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RBSP_BYTE                    FVV_DESCRIPTOR_B
#define FVV_DESCRIPTOR_NAL_FORBIDDEN_ZERO_BIT       FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_NAL_UNIT_TYPE                FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_NAL_LAYER_ID                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_NAL_TEMPORAL_ID_PLUS1        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_ATLAS_SEQUENCE_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_FRAME_WIDTH  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_FRAME_HEIGHT FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_GEOMETRY_3D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_GEOMETRY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_LOG2_MAX_ATLAS_FRAME_ORDER_CNT_LSB_MINUS4 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_MAX_DEC_ATLAS_FRAME_BUFFERING_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_LONG_TERM_REF_ATLAS_FRAMES_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_NUM_REF_ATLAS_FRAME_LISTS_IN_ASPS \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_USE_EIGHT_ORIENTATIONS_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENDED_PROJECTION_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAX_NUMBER_PROJECTIONS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_NORMAL_AXIS_LIMITS_QUANTIZATION_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_NORMAL_AXIS_MAX_DELTA_VALUE_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PATCH_PRECEDENCE_ORDER_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_LOG2_PATCH_PACKING_BLOCK_SIZE \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PATCH_SIZE_QUANTIZER_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAP_COUNT_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PIXEL_DEINTERLEAVING_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAP_PIXEL_DEINTERLEAVING_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_RAW_PATCH_ENABLED_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EOM_PATCH_ENABLED_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EOM_FIX_BIT_COUNT_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_AUXILIARY_VIDEO_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PLR_ENABLED_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_VUI_PARAMETERS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_VPCC_EXTENSION_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_7BITS        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_DATA_FLAG    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_MAP_PRESENT_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_NUMBER_OF_MODES_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_INTERPOLATE_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_FILLING_FLAG           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_MINIMUM_DEPTH          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_NEIGHBOUR_MINUS1       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_BLOCK_THRESHOLD_PER_PATCH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_ATLAS_FRAME_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_ATLAS_SEQUENCE_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_OUTPUT_FLAG_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_NUM_REF_IDX_DEFAULT_ACTIVE_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_ADDITIONAL_LT_AFOC_LSB_LEN \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_LOD_MODE_ENABLED_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_RAW_3D_OFFSET_BIT_COUNT_EXPLICIT_MODE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_8BITS        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_DATA_FLAG    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_SINGLE_TILE_IN_ATLAS_FRAME_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_UNIFORM_PARTITION_SPACING_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_PARTITION_COLS_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_ROWS_HEIGHT_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_NUM_PARTITION_COLUMNS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_NUM_PARTITION_ROWS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_COLUMN_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_ROW_HEIGHT_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_SINGLE_PARTITION_PER_TILE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_NUM_TILES_IN_ATLAS_FRAME_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_TOP_LEFT_PARTITION_IDX FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_BOTTOM_RIGHT_PARTITION_COLUMN_OFFSET \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_BOTTOM_RIGHT_PARTITION_ROW_OFFSET \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_AUXILIARY_VIDEO_TILE_ROW_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_AUXILIARY_VIDEO_TILE_ROW_HEIGHT \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_SIGNALLED_TILE_ID_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_SIGNALLED_TILE_ID_LENGTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_TILE_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AAPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_VPCC_EXTENSION_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_EXTENSION_7BITS     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_EXTENSION_DATA_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFRAME_TYPE              FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_FF_BYTE                  FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_RBSP_STOP_ONE_BIT        FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_RBSP_ALIGNMENT_ZERO_BIT  FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_ATH_NO_OUTPUT_OF_PRIOR_ATLAS_FRAMES_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ATLAS_FRAME_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ID                      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_TYPE                    FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ATLAS_OUTPUT_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ATLAS_FRM_ORDER_CNT_LSB FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_REF_ATLAS_FRAME_LIST_ASPS_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_REF_ATLAS_FRAME_LIST_IDX FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ADDITIONAL_AFOC_LSB_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ADDITIONAL_AFOC_LSB_VAL   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_POS_MIN_D_QUANTIZER       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_POS_DELTA_MAX_D_QUANTIZER FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_PATCH_SIZE_X_INFO_QUANTIZER \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_PATCH_SIZE_Y_INFO_QUANTIZER \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_RAW_3D_OFFSET_AXIS_BIT_COUNT_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_NUM_REF_IDX_ACTIVE_OVERRIDE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_NUM_REF_IDX_ACTIVE_MINUS1 FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_NUM_REF_ENTRIES               FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ST_REF_ATLAS_FRAME_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ABS_DELTA_AFOC_ST             FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_STRAF_ENTRY_SIGN_FLAG         FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFOC_LSB_LT                   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_VPCC_CAMERA_PARAMETERS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_CAMERA_MODEL          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_SCALE_ENABLED_FLAG    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_OFFSET_ENABLED_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_ROTATION_ENABLED_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_SCALE_ON_AXIS         FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ACP_OFFSET_ON_AXIS        FVV_DESCRIPTOR_I
#define FVV_DESCRIPTOR_ACP_ROTATION_QX           FVV_DESCRIPTOR_I
#define FVV_DESCRIPTOR_ACP_ROTATION_QY           FVV_DESCRIPTOR_I
#define FVV_DESCRIPTOR_ACP_ROTATION_QZ           FVV_DESCRIPTOR_I
#define FVV_DESCRIPTOR_ASPS_VPCC_REMOVE_DUPLICATE_POINT_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_VPCC_SURFACE_THICKNESS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATDU_PATCH_MODE              FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_MPDU_REF_INDEX               FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_MPDU_OVERRIDE_2D_PARAMS_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_MPDU_2D_POS_X                FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_2D_POS_Y                FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_2D_DELTA_SIZE_X         FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_2D_DELTA_SIZE_Y         FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_OVERRIDE_3D_PARAMS_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_MPDU_3D_OFFSET_U             FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_3D_OFFSET_V             FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_3D_OFFSET_D             FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_3D_RANGE_D              FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_MPDU_OVERRIDE_PLR_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_EPDU_PATCH_IN_AUXILIARY_VIDEO_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_EPDU_2D_POS_X             FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_2D_POS_Y             FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_2D_SIZE_X_MINUS1     FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_2D_SIZE_Y_MINUS1     FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_PATCH_COUNT_MINUS1   FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_ASSOCIATED_PATCH_IDX FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_EPDU_POINTS               FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_IPDU_REF_INDEX            FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_IPDU_PATCH_INDEX          FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_2D_POS_X             FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_2D_POS_Y             FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_2D_DELTA_SIZE_X      FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_2D_DELTA_SIZE_Y      FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_3D_OFFSET_U          FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_3D_OFFSET_V          FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_3D_OFFSET_D          FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_IPDU_3D_RANGE_D           FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_PDU_2D_POS_X              FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PDU_2D_POS_Y              FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PDU_2D_SIZE_X_MINUS1      FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PDU_2D_SIZE_Y_MINUS1      FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PDU_3D_OFFSET_U           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_3D_OFFSET_V           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_3D_OFFSET_D           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_3D_RANGE_D            FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_PROJECTION_ID         FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_ORIENTATION_INDEX     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_LOD_ENABLED_FLAG      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PDU_LOD_SCALE_X_MINUS1    FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PDU_LOD_SCALE_Y_IDC       FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_PLRD_LEVEL                FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRD_PRESENT_BLOCK_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRD_PRESENT_FLAG         FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRD_BLOCK_MODE_MINUS1    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRD_MODE_MINUS1          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RPDU_PATCH_IN_AUXILIARY_VIDEO_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RPDU_2D_POS_X         FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_RPDU_2D_POS_Y         FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_RPDU_2D_SIZE_X_MINUS1 FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_RPDU_2D_SIZE_Y_MINUS1 FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_RPDU_3D_OFFSET_U      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RPDU_3D_OFFSET_V      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RPDU_3D_OFFSET_D      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RPDU_POINTS_MINUS1    FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_SM_PAYLOAD_TYPE_BYTE  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SM_PAYLOAD_SIZE_BYTE  FVV_DESCRIPTOR_U

typedef enum
{
  FVV_V3C_VPS  = 0, // V3C parameter set
  FVV_V3C_AD   = 1, // Atlas data
  FVV_V3C_OVD  = 2, // Occupancy video data
  FVV_V3C_GVD  = 3, // Geometry video data
  FVV_V3C_AVD  = 4, // Attribute video data
  FVV_V3C_RSVD = 5  // Reserved, values 5..31
} fvv_vuh_unit_type_e;

typedef enum
{
  FVV_ATTR_TEXTURE      = 0, // Texture
  FVV_ATTR_MATERIAL_ID  = 1, // Material ID
  FVV_ATTR_TRANSPARENCY = 2, // Transparency
  FVV_ATTR_REFLECTANCE  = 3, // Reflectance
  FVV_ATTR_NORMAL       = 4, // Normals
  ATTR_RESERVED         = 5, // Reserved, value 5..14
  ATTR_UNSPECIFIED      = 15 // Unspecified
} fvv_ai_attribute_type_id_e;

typedef enum
{
  // Trailing atlas frame tiles
  FVV_NAL_TRAIL_N         = 0,
  FVV_NAL_TRAIL_R         = 1,
  FVV_NAL_TSA_N           = 2,
  FVV_NAL_TSA_R           = 3,
  FVV_NAL_STSA_N          = 4,
  FVV_NAL_STSA_R          = 5,
  FVV_NAL_RADL_N          = 6,
  FVV_NAL_RADL_R          = 7,
  FVV_NAL_RASL_N          = 8,
  FVV_NAL_RASL_R          = 9,

  // Skipped frames
  FVV_NAL_SKIP_N          = 10,
  FVV_NAL_SKIP_R          = 11,

  // Reserved ACL (non-IRAP)
  FVV_NAL_RSV_ACL_N12     = 12,
  FVV_NAL_RSV_ACL_R13     = 13,
  FVV_NAL_RSV_ACL_N14     = 14,
  FVV_NAL_RSV_ACL_R15     = 15,

  // BLA frames
  FVV_NAL_BLA_W_LP        = 16,
  FVV_NAL_BLA_W_RADL      = 17,
  FVV_NAL_BLA_N_LP        = 18,

  // GBLA frames
  FVV_NAL_GBLA_W_LP       = 19,
  FVV_NAL_GBLA_W_RADL     = 20,
  FVV_NAL_GBLA_N_LP       = 21,

  // IDR & GIDR frames
  FVV_NAL_IDR_W_RADL      = 22,
  FVV_NAL_IDR_N_LP        = 23,
  FVV_NAL_GIDR_W_RADL     = 24,
  FVV_NAL_GIDR_N_LP       = 25,

  // CRA & GCRA frames
  FVV_NAL_CRA             = 26,
  FVV_NAL_GCRA            = 27,

  // Reserved IRAP ACL
  FVV_NAL_RSV_IRAP_ACL_28 = 28,
  FVV_NAL_RSV_IRAP_ACL_29 = 29,

  // Reserved non-IRAP ACL
  FVV_NAL_RSV_ACL_30      = 30,
  FVV_NAL_RSV_ACL_31      = 31,
  FVV_NAL_RSV_ACL_32      = 32,
  FVV_NAL_RSV_ACL_33      = 33,
  FVV_NAL_RSV_ACL_34      = 34,
  FVV_NAL_RSV_ACL_35      = 35,

  // Non-ACL NAL unit types
  FVV_NAL_ASPS            = 36,
  FVV_NAL_AFPS            = 37,
  FVV_NAL_AUD             = 38,
  FVV_NAL_V3C_AUD         = 39,
  FVV_NAL_EOS             = 40,
  FVV_NAL_EOB             = 41,
  FVV_NAL_FD              = 42,
  FVV_NAL_PREFIX_NSEI     = 43,
  FVV_NAL_SUFFIX_NSEI     = 44,
  FVV_NAL_PREFIX_ESEI     = 45,
  FVV_NAL_SUFFIX_ESEI     = 46,
  FVV_NAL_AAPS            = 47,

  // Reserved non-ACL
  FVV_NAL_RSV_NACL_48     = 48,
  FVV_NAL_RSV_NACL_49     = 49,
  FVV_NAL_RSV_NACL_50     = 50,
  FVV_NAL_RSV_NACL_51     = 51,
  FVV_NAL_RSV_NACL_52     = 52,

  // Unspecified
  FVV_NAL_UNSPEC_53       = 53,
  FVV_NAL_UNSPEC_54       = 54,
  FVV_NAL_UNSPEC_55       = 55,
  FVV_NAL_UNSPEC_56       = 56,
  FVV_NAL_UNSPEC_57       = 57,
  FVV_NAL_UNSPEC_58       = 58,
  FVV_NAL_UNSPEC_59       = 59,
  FVV_NAL_UNSPEC_60       = 60,
  FVV_NAL_UNSPEC_61       = 61,
  FVV_NAL_UNSPEC_62       = 62,
  FVV_NAL_UNSPEC_63       = 63
} fvv_nal_unit_type_e;

typedef enum
{
  FVV_P_TILE    = 0,
  FVV_I_TILE    = 1,
  FVV_SKIP_TILE = 2,
  FVV_RESERVED  = 3, // Reserved, values 3..7
} fvv_ath_type_e;

typedef enum
{
  FVV_I_INTRA    = 0, // Non-predicted patch mode
  FVV_I_RAW      = 1, // RAW Point Patch mode
  FVV_I_EOM      = 2, // EOM Point Patch mode
  FVV_I_RESERVED = 3, // Reserved modes for future use by ISO/IEC
  FVV_I_END      = 14 // Patch termination mode
} fvv_atdu_patch_mode_i_tile_e;

typedef enum
{
  FVV_P_SKIP     = 0, // Patch Skip mode
  FVV_P_MERGE    = 1, // Patch Merge mode
  FVV_P_INTER    = 2, // Inter predicted Patch mode
  FVV_P_INTRA    = 3, // Non-predicted Patch mode
  FVV_P_RAW      = 4, // RAW Point Patch mode
  FVV_P_EOM      = 5, // EOM Point Patch mode
  FVV_P_RESERVED = 6, // Reserved modes for future use by ISO/IEC
  FVV_P_END      = 14 // Patch termination mode
} fvv_atdu_patch_mode_p_tile_e;

// typedef enum
// {
//   FVV_P_SKIP = 0, // Patch Skip mode
// } fvv_atdu_patch_mode_skip_tile_e;

#endif
