#ifndef FVV_SEMANTIC_H
#define FVV_SEMANTIC_H

// Bit size type
#define FVV_BIT_VARIABLE                                          0
// Bit size
#define FVV_BIT_TRAILING_ZERO_8BITS                               8
#define FVV_BIT_VUH_UNIT_TYPE                                     5
#define FVV_BIT_VUH_V3C_PARAMETER_SET_ID                          4
#define FVV_BIT_VUH_ATLAS_ID                                      6
#define FVV_BIT_VUH_ATTRIBUTE_INDEX                               7
#define FVV_BIT_VUH_ATTRIBUTE_PARTITION_INDEX                     5
#define FVV_BIT_VUH_MAP_INDEX                                     4
#define FVV_BIT_VUH_AUXILIARY_VIDEO_FLAG                          1
#define FVV_BIT_VUH_RESERVED_ZERO_12BITS                          12
#define FVV_BIT_VUH_RESERVED_ZERO_17BITS                          17
#define FVV_BIT_VUH_RESERVED_ZERO_27BITS                          27
#define FVV_BIT_ALIGNMENT_BIT_EQUAL_TO_ONE                        1
#define FVV_BIT_ALIGNMENT_BIT_EQUAL_TO_ZERO                       1
#define FVV_BIT_VPS_V3C_PARAMETER_SET_ID                          4
#define FVV_BIT_VPS_RESERVED_ZERO_8BITS                           8
#define FVV_BIT_VPS_ATLAS_COUNT_MINUS1                            6
#define FVV_BIT_VPS_ATLAS_ID                                      6
#define FVV_BIT_VPS_FRAME_WIDTH                                   FVV_BIT_VARIABLE
#define FVV_BIT_VPS_FRAME_HEIGHT                                  FVV_BIT_VARIABLE
#define FVV_BIT_VPS_MAP_COUNT_MINUS1                              4
#define FVV_BIT_VPS_MULTIPLE_MAP_STREAMS_PRESENT_FLAG             1
#define FVV_BIT_VPS_MAP_ABSOLUTE_CODING_ENABLED_FLAG              1
#define FVV_BIT_VPS_MAP_PREDICTOR_INDEX_DIFF                      FVV_BIT_VARIABLE
#define FVV_BIT_VPS_AUXILIARY_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_OCCUPANCY_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_GEOMETRY_VIDEO_PRESENT_FLAG                   1
#define FVV_BIT_VPS_ATTRIBUTE_VIDEO_PRESENT_FLAG                  1
#define FVV_BIT_VPS_EXTENSION_PRESENT_FLAG                        1
#define FVV_BIT_VPS_EXTENSION_8BITS                               8
#define FVV_BIT_VPS_EXTENSION_LENGTH_MINUS1                       FVV_BIT_VARIABLE
#define FVV_BIT_VPS_EXTENSION_DATA_BYTE                           8
#define FVV_BIT_PTL_TIER_FLAG                                     1
#define FVV_BIT_PTL_PROFILE_CODEC_GROUP_IDC                       7
#define FVV_BIT_PTL_PROFILE_TOOLSET_IDC                           8
#define FVV_BIT_PTL_PROFILE_RECONSTRUCTION_IDC                    8
#define FVV_BIT_PTL_RESERVED_ZERO_16BITS                          16
#define FVV_BIT_PTL_RESERVED_0XFFFF_16BITS                        16
#define FVV_BIT_PTL_LEVEL_IDC                                     8
#define FVV_BIT_PTL_NUM_SUB_PROFILES                              6
#define FVV_BIT_PTL_EXTENDED_SUB_PROFILE_FLAG                     1
#define FVV_BIT_PTL_SUB_PROFILE_IDC                               FVV_BIT_VARIABLE
#define FVV_BIT_PTL_TOOL_CONSTRAINTS_PRESENT_FLAG                 1
#define FVV_BIT_SSNH_UNIT_SIZE_PRECISION_BYTES_MINUS1             3
#define FVV_BIT_SSNH_RESERVED_ZERO_5BITS                          5
#define FVV_BIT_SSNU_NAL_UNIT_SIZE                                FVV_BIT_VARIABLE
#define FVV_BIT_OI_OCCUPANCY_CODEC_ID                             8
#define FVV_BIT_OI_LOSSY_OCCUPANCY_COMPRESSION_THRESHOLD          8
#define FVV_BIT_OI_OCCUPANCY_2D_BIT_DEPTH_MINUS1                  5
#define FVV_BIT_OI_OCCUPANCY_MSB_ALIGN_FLAG                       1
#define FVV_BIT_GI_GEOMETRY_CODEC_ID                              8
#define FVV_BIT_GI_GEOMETRY_2D_BIT_DEPTH_MINUS1                   5
#define FVV_BIT_GI_GEOMETRY_MSB_ALIGN_FLAG                        1
#define FVV_BIT_GI_GEOMETRY_3D_COORDINATES_BIT_DEPTH_MINUS1       5
#define FVV_BIT_GI_AUXILIARY_GEOMETRY_CODEC_ID                    8
#define FVV_BIT_AI_ATTRIBUTE_COUNT                                7
#define FVV_BIT_AI_ATTRIBUTE_TYPE_ID                              4
#define FVV_BIT_AI_ATTRIBUTE_CODEC_ID                             8
#define FVV_BIT_AI_AUXILIARY_ATTRIBUTE_CODEC_ID                   8
#define FVV_BIT_AI_ATTRIBUTE_MAP_ABSOLUTE_CODING_PERSISTENCE_FLAG 1
#define FVV_BIT_AI_ATTRIBUTE_DIMENSION_MINUS1                     6
#define FVV_BIT_AI_ATTRIBUTE_DIMENSION_PARTITIONS_MINUS1          6
#define FVV_BIT_AI_ATTRIBUTE_PARTITION_CHANNELS_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AI_ATTRIBUTE_2D_BIT_DEPTH_MINUS1                 5
#define FVV_BIT_AI_ATTRIBUTE_MSB_ALIGN_FLAG                      1
#define FVV_BIT_PTC_ONE_V3C_FRAME_ONLY_FLAG                      1
#define FVV_BIT_PTC_EOM_CONSTRAINT_FLAG                          1
#define FVV_BIT_PTC_MAX_MAP_COUNT_MINUS1                         4
#define FVV_BIT_PTC_MAX_ATLAS_COUNT_MINUS1                       4
#define FVV_BIT_PTC_MULTIPLE_MAP_STREAMS_CONSTRAINT_FLAG         1
#define FVV_BIT_PTC_PLR_CONSTRAINT_FLAG                          1
#define FVV_BIT_PTC_ATTRIBUTE_MAX_DIMENSION_MINUS1               6
#define FVV_BIT_PTC_ATTRIBUTE_MAX_DIMENSION_PARTITIONS_MINUS1    6
#define FVV_BIT_PTC_NO_EIGHT_ORIENTATIONS_CONSTRAINT_FLAG        1
#define FVV_BIT_PTC_NO_45DEGREE_PROJECTION_PATCH_CONSTRAINT_FLAG 1
#define FVV_BIT_PTC_RESERVED_ZERO_6BITS                          6
#define FVV_BIT_PTC_NUM_RESERVED_CONSTRAINT_BYTES                8
#define FVV_BIT_PTC_RESERVED_CONSTRAINT_BYTE                     8
#define FVV_BIT_RBSP_BYTE                                        8
#define FVV_BIT_NAL_FORBIDDEN_ZERO_BIT                           1
#define FVV_BIT_NAL_UNIT_TYPE                                    6
#define FVV_BIT_NAL_LAYER_ID                                     6
#define FVV_BIT_NAL_TEMPORAL_ID_PLUS1                            3
#define FVV_BIT_ASPS_ATLAS_SEQUENCE_PARAMETER_SET_ID             FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_FRAME_WIDTH                                 FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_FRAME_HEIGHT                                FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_GEOMETRY_3D_BIT_DEPTH_MINUS1                5
#define FVV_BIT_ASPS_GEOMETRY_2D_BIT_DEPTH_MINUS1                5
#define FVV_BIT_ASPS_LOG2_MAX_ATLAS_FRAME_ORDER_CNT_LSB_MINUS4 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_MAX_DEC_ATLAS_FRAME_BUFFERING_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_LONG_TERM_REF_ATLAS_FRAMES_FLAG 1
#define FVV_BIT_ASPS_NUM_REF_ATLAS_FRAME_LISTS_IN_ASPS \
  FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_USE_EIGHT_ORIENTATIONS_FLAG                  1
#define FVV_BIT_ASPS_EXTENDED_PROJECTION_ENABLED_FLAG             1
#define FVV_BIT_ASPS_MAX_NUMBER_PROJECTIONS_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_ASPS_NORMAL_AXIS_LIMITS_QUANTIZATION_ENABLED_FLAG 1
#define FVV_BIT_ASPS_NORMAL_AXIS_MAX_DELTA_VALUE_ENABLED_FLAG     1
#define FVV_BIT_ASPS_PATCH_PRECEDENCE_ORDER_FLAG                  1
#define FVV_BIT_ASPS_LOG2_PATCH_PACKING_BLOCK_SIZE                3
#define FVV_BIT_ASPS_PATCH_SIZE_QUANTIZER_PRESENT_FLAG            1
#define FVV_BIT_ASPS_MAP_COUNT_MINUS1                             4
#define FVV_BIT_ASPS_PIXEL_DEINTERLEAVING_ENABLED_FLAG            1
#define FVV_BIT_ASPS_MAP_PIXEL_DEINTERLEAVING_FLAG                1
#define FVV_BIT_ASPS_RAW_PATCH_ENABLED_FLAG                       1
#define FVV_BIT_ASPS_EOM_PATCH_ENABLED_FLAG                       1
#define FVV_BIT_ASPS_EOM_FIX_BIT_COUNT_MINUS1                     4
#define FVV_BIT_ASPS_AUXILIARY_VIDEO_ENABLED_FLAG                 1
#define FVV_BIT_ASPS_PLR_ENABLED_FLAG                             1
#define FVV_BIT_ASPS_VUI_PARAMETERS_PRESENT_FLAG                  1
#define FVV_BIT_ASPS_EXTENSION_PRESENT_FLAG                       1
#define FVV_BIT_ASPS_VPCC_EXTENSION_PRESENT_FLAG                  1
#define FVV_BIT_ASPS_EXTENSION_7BITS                              7
#define FVV_BIT_ASPS_EXTENSION_DATA_FLAG                          1
#define FVV_BIT_PLRI_MAP_PRESENT_FLAG                             1
#define FVV_BIT_PLRI_NUMBER_OF_MODES_MINUS1                       4
#define FVV_BIT_PLRI_INTERPOLATE_FLAG                             1
#define FVV_BIT_PLRI_FILLING_FLAG                                 1
#define FVV_BIT_PLRI_MINIMUM_DEPTH                                2
#define FVV_BIT_PLRI_NEIGHBOUR_MINUS1                             2
#define FVV_BIT_PLRI_BLOCK_THRESHOLD_PER_PATCH_MINUS1             6
#define FVV_BIT_AFPS_ATLAS_FRAME_PARAMETER_SET_ID                 FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_ATLAS_SEQUENCE_PARAMETER_SET_ID              FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_OUTPUT_FLAG_PRESENT_FLAG                     1
#define FVV_BIT_AFPS_NUM_REF_IDX_DEFAULT_ACTIVE_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_ADDITIONAL_LT_AFOC_LSB_LEN                 FVV_BIT_VARIABLE
#define FVV_BIT_AFPS_LOD_MODE_ENABLED_FLAG                      1
#define FVV_BIT_AFPS_RAW_3D_OFFSET_BIT_COUNT_EXPLICIT_MODE_FLAG 1
#define FVV_BIT_AFPS_EXTENSION_PRESENT_FLAG                     1
#define FVV_BIT_AFPS_EXTENSION_8BITS                            8
#define FVV_BIT_AFPS_EXTENSION_DATA_FLAG                        1
#define FVV_BIT_AFTI_SINGLE_TILE_IN_ATLAS_FRAME_FLAG            1
#define FVV_BIT_AFTI_UNIFORM_PARTITION_SPACING_FLAG             1
#define FVV_BIT_AFTI_PARTITION_COLS_WIDTH_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_ROWS_HEIGHT_MINUS1               FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_NUM_PARTITION_COLUMNS_MINUS1               FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_NUM_PARTITION_ROWS_MINUS1                  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_COLUMN_WIDTH_MINUS1              FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_PARTITION_ROW_HEIGHT_MINUS1                FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_SINGLE_PARTITION_PER_TILE_FLAG             1
#define FVV_BIT_AFTI_NUM_TILES_IN_ATLAS_FRAME_MINUS1            FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_TOP_LEFT_PARTITION_IDX                     FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_BOTTOM_RIGHT_PARTITION_COLUMN_OFFSET \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_BOTTOM_RIGHT_PARTITION_ROW_OFFSET \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_AUXILIARY_VIDEO_TILE_ROW_WIDTH_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_AUXILIARY_VIDEO_TILE_ROW_HEIGHT FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_SIGNALLED_TILE_ID_FLAG          1
#define FVV_BIT_AFTI_SIGNALLED_TILE_ID_LENGTH_MINUS1 FVV_BIT_VARIABLE
#define FVV_BIT_AFTI_TILE_ID                         FVV_BIT_VARIABLE
#define FVV_BIT_AAPS_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_BIT_VARIABLE
#define FVV_BIT_AAPS_EXTENSION_PRESENT_FLAG              1
#define FVV_BIT_AAPS_VPCC_EXTENSION_PRESENT_FLAG         1
#define FVV_BIT_AAPS_EXTENSION_7BITS                     7
#define FVV_BIT_AAPS_EXTENSION_DATA_FLAG                 1
#define FVV_BIT_AFRAME_TYPE                              3
#define FVV_BIT_FF_BYTE                                  8
#define FVV_BIT_RBSP_STOP_ONE_BIT                        1
#define FVV_BIT_RBSP_ALIGNMENT_ZERO_BIT                  1
#define FVV_BIT_ATH_NO_OUTPUT_OF_PRIOR_ATLAS_FRAMES_FLAG 1
#define FVV_BIT_ATH_ATLAS_FRAME_PARAMETER_SET_ID         FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ID                               FVV_BIT_VARIABLE
#define FVV_BIT_ATH_TYPE                             FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ATLAS_OUTPUT_FLAG                1
#define FVV_BIT_ATH_ATLAS_FRM_ORDER_CNT_LSB          FVV_BIT_VARIABLE
#define FVV_BIT_ATH_REF_ATLAS_FRAME_LIST_ASPS_FLAG   1
#define FVV_BIT_ATH_REF_ATLAS_FRAME_LIST_IDX         FVV_BIT_VARIABLE
#define FVV_BIT_ATH_ADDITIONAL_AFOC_LSB_PRESENT_FLAG 1
#define FVV_BIT_ATH_ADDITIONAL_AFOC_LSB_VAL          FVV_BIT_VARIABLE
#define FVV_BIT_ATH_POS_MIN_D_QUANTIZER              5
#define FVV_BIT_ATH_POS_DELTA_MAX_D_QUANTIZER        5
#define FVV_BIT_ATH_PATCH_SIZE_X_INFO_QUANTIZER      3
#define FVV_BIT_ATH_PATCH_SIZE_Y_INFO_QUANTIZER      3
#define FVV_BIT_ATH_RAW_3D_OFFSET_AXIS_BIT_COUNT_MINUS1 \
  FVV_BIT_VARIABLE
#define FVV_BIT_ATH_NUM_REF_IDX_ACTIVE_OVERRIDE_FLAG 1
#define FVV_BIT_ATH_NUM_REF_IDX_ACTIVE_MINUS1        FVV_BIT_VARIABLE
#define FVV_BIT_NUM_REF_ENTRIES                      FVV_BIT_VARIABLE
#define FVV_BIT_ST_REF_ATLAS_FRAME_FLAG              1
#define FVV_BIT_ABS_DELTA_AFOC_ST                    FVV_BIT_VARIABLE
#define FVV_BIT_STRAF_ENTRY_SIGN_FLAG                1
#define FVV_BIT_AFOC_LSB_LT                          FVV_BIT_VARIABLE

// Descriptors type
#define FVV_DESCRIPTOR_B
#define FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_FL
#define FVV_DESCRIPTOR_I
#define FVV_DESCRIPTOR_SE
#define FVV_DESCRIPTOR_ST
#define FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_UE
// Descriptors

#define FVV_DESCRIPTOR_VUH_UNIT_TYPE                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_V3C_PARAMETER_SET_ID      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATLAS_ID                  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATTRIBUTE_INDEX           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_ATTRIBUTE_PARTITION_INDEX FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_MAP_INDEX                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_AUXILIARY_VIDEO_FLAG      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_12BITS      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_17BITS      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VUH_RESERVED_ZERO_27BITS      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ALIGNMENT_BIT_EQUAL_TO_ONE    FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_ALIGNMENT_BIT_EQUAL_TO_ZERO   FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_VPS_V3C_PARAMETER_SET_ID      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_RESERVED_ZERO_8BITS       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATLAS_COUNT_MINUS1        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATLAS_ID                  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_FRAME_WIDTH               FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_FRAME_HEIGHT              FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_MAP_COUNT_MINUS1          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MULTIPLE_MAP_STREAMS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MAP_ABSOLUTE_CODING_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_MAP_PREDICTOR_INDEX_DIFF FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_AUXILIARY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_OCCUPANCY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_GEOMETRY_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_ATTRIBUTE_VIDEO_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_PRESENT_FLAG  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_8BITS         FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_VPS_EXTENSION_LENGTH_MINUS1 FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_VPS_EXTENSION_DATA_BYTE     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_TIER_FLAG               FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_CODEC_GROUP_IDC FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_TOOLSET_IDC     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_PROFILE_RECONSTRUCTION_IDC \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_RESERVED_ZERO_16BITS      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_RESERVED_0XFFFF_16BITS    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_LEVEL_IDC                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_NUM_SUB_PROFILES          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_EXTENDED_SUB_PROFILE_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_SUB_PROFILE_IDC           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTL_TOOL_CONSTRAINTS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNH_UNIT_SIZE_PRECISION_BYTES_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNH_RESERVED_ZERO_5BITS FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_SSNU_NAL_UNIT_SIZE       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_LOSSY_OCCUPANCY_COMPRESSION_THRESHOLD \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_CODEC_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_OI_OCCUPANCY_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_CODEC_ID        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_GEOMETRY_3D_COORDINATES_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_GI_AUXILIARY_GEOMETRY_CODEC_ID \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_COUNT    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_TYPE_ID  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_CODEC_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_AUXILIARY_ATTRIBUTE_CODEC_ID \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_MAP_ABSOLUTE_CODING_PERSISTENCE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_DIMENSION_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_DIMENSION_PARTITIONS_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_PARTITION_CHANNELS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AI_ATTRIBUTE_MSB_ALIGN_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ONE_V3C_FRAME_ONLY_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_EOM_CONSTRAINT_FLAG     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MAX_MAP_COUNT_MINUS1    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MAX_ATLAS_COUNT_MINUS1  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_MULTIPLE_MAP_STREAMS_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_PLR_CONSTRAINT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ATTRIBUTE_MAX_DIMENSION_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_ATTRIBUTE_MAX_DIMENSION_PARTITIONS_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NO_EIGHT_ORIENTATIONS_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NO_45DEGREE_PROJECTION_PATCH_CONSTRAINT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_RESERVED_ZERO_6BITS FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_NUM_RESERVED_CONSTRAINT_BYTES \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PTC_RESERVED_CONSTRAINT_BYTE FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_RBSP_BYTE                    FVV_DESCRIPTOR_B
#define FVV_DESCRIPTOR_NAL_FORBIDDEN_ZERO_BIT       FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_NAL_UNIT_TYPE                FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_NAL_LAYER_ID                 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_NAL_TEMPORAL_ID_PLUS1        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_ATLAS_SEQUENCE_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_FRAME_WIDTH  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_FRAME_HEIGHT FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_GEOMETRY_3D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_GEOMETRY_2D_BIT_DEPTH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_LOG2_MAX_ATLAS_FRAME_ORDER_CNT_LSB_MINUS4 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_MAX_DEC_ATLAS_FRAME_BUFFERING_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_LONG_TERM_REF_ATLAS_FRAMES_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_NUM_REF_ATLAS_FRAME_LISTS_IN_ASPS \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_USE_EIGHT_ORIENTATIONS_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENDED_PROJECTION_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAX_NUMBER_PROJECTIONS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ASPS_NORMAL_AXIS_LIMITS_QUANTIZATION_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_NORMAL_AXIS_MAX_DELTA_VALUE_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PATCH_PRECEDENCE_ORDER_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_LOG2_PATCH_PACKING_BLOCK_SIZE \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PATCH_SIZE_QUANTIZER_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAP_COUNT_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PIXEL_DEINTERLEAVING_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_MAP_PIXEL_DEINTERLEAVING_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_RAW_PATCH_ENABLED_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EOM_PATCH_ENABLED_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EOM_FIX_BIT_COUNT_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_AUXILIARY_VIDEO_ENABLED_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_PLR_ENABLED_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_VUI_PARAMETERS_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_VPCC_EXTENSION_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_7BITS        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ASPS_EXTENSION_DATA_FLAG    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_MAP_PRESENT_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_NUMBER_OF_MODES_MINUS1 FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_INTERPOLATE_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_FILLING_FLAG           FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_MINIMUM_DEPTH          FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_NEIGHBOUR_MINUS1       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_PLRI_BLOCK_THRESHOLD_PER_PATCH_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_ATLAS_FRAME_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_ATLAS_SEQUENCE_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_OUTPUT_FLAG_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_NUM_REF_IDX_DEFAULT_ACTIVE_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_ADDITIONAL_LT_AFOC_LSB_LEN \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFPS_LOD_MODE_ENABLED_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_RAW_3D_OFFSET_BIT_COUNT_EXPLICIT_MODE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_8BITS        FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFPS_EXTENSION_DATA_FLAG    FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_SINGLE_TILE_IN_ATLAS_FRAME_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_UNIFORM_PARTITION_SPACING_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_PARTITION_COLS_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_ROWS_HEIGHT_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_NUM_PARTITION_COLUMNS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_NUM_PARTITION_ROWS_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_COLUMN_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_PARTITION_ROW_HEIGHT_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_SINGLE_PARTITION_PER_TILE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_NUM_TILES_IN_ATLAS_FRAME_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_TOP_LEFT_PARTITION_IDX FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_BOTTOM_RIGHT_PARTITION_COLUMN_OFFSET \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_BOTTOM_RIGHT_PARTITION_ROW_OFFSET \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_AUXILIARY_VIDEO_TILE_ROW_WIDTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_AUXILIARY_VIDEO_TILE_ROW_HEIGHT \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_SIGNALLED_TILE_ID_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFTI_SIGNALLED_TILE_ID_LENGTH_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AFTI_TILE_ID FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_AAPS_EXTENSION_PRESENT_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_VPCC_EXTENSION_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_EXTENSION_7BITS     FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AAPS_EXTENSION_DATA_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFRAME_TYPE              FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_FF_BYTE                  FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_RBSP_STOP_ONE_BIT        FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_RBSP_ALIGNMENT_ZERO_BIT  FVV_DESCRIPTOR_F
#define FVV_DESCRIPTOR_ATH_NO_OUTPUT_OF_PRIOR_ATLAS_FRAMES_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ATLAS_FRAME_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ATLAS_ADAPTATION_PARAMETER_SET_ID \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ID                      FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_TYPE                    FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ATH_ATLAS_OUTPUT_FLAG       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ATLAS_FRM_ORDER_CNT_LSB FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_REF_ATLAS_FRAME_LIST_ASPS_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_REF_ATLAS_FRAME_LIST_IDX FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ADDITIONAL_AFOC_LSB_PRESENT_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_ADDITIONAL_AFOC_LSB_VAL   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_POS_MIN_D_QUANTIZER       FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_POS_DELTA_MAX_D_QUANTIZER FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_PATCH_SIZE_X_INFO_QUANTIZER \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_PATCH_SIZE_Y_INFO_QUANTIZER \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_RAW_3D_OFFSET_AXIS_BIT_COUNT_MINUS1 \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_NUM_REF_IDX_ACTIVE_OVERRIDE_FLAG \
  FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ATH_NUM_REF_IDX_ACTIVE_MINUS1 \
  FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_NUM_REF_ENTRIES         FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_ST_REF_ATLAS_FRAME_FLAG FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_ABS_DELTA_AFOC_ST       FVV_DESCRIPTOR_UE
#define FVV_DESCRIPTOR_STRAF_ENTRY_SIGN_FLAG   FVV_DESCRIPTOR_U
#define FVV_DESCRIPTOR_AFOC_LSB_LT             FVV_DESCRIPTOR_U

typedef enum
{
  FVV_V3C_VPS  = 0, // V3C parameter set
  FVV_V3C_AD   = 1, // Atlas data
  FVV_V3C_OVD  = 2, // Occupancy video data
  FVV_V3C_GVD  = 3, // Geometry video data
  FVV_V3C_AVD  = 4, // Attribute video data
  FVV_V3C_RSVD = 5  // Reserved, values 5..31
} fvv_vuh_unit_type_e;

#endif