#ifndef FVV_SYNTAX_ATLAS_SEQUENCE_PARAMETER_SET_RBSP_H
#define FVV_SYNTAX_ATLAS_SEQUENCE_PARAMETER_SET_RBSP_H

#include <fvv/defs.h>
#include <fvv/semantic.h>

// 8.3.6.1.1 General atlas sequence parameter set RBSP syntax
struct fvv_atlas_sequence_parameter_set_rbsp_t
{
  fvv_bitstream_t *data;

  fvv_ret_t (*pack)(fvv_atlas_sequence_parameter_set_rbsp_t *self);
  fvv_ret_t (*copy_from)(
      fvv_atlas_sequence_parameter_set_rbsp_t *self,
      fvv_atlas_sequence_parameter_set_rbsp_t *other);

  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_atlas_sequence_parameter_set_id);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_frame_width);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_frame_height);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_geometry_3d_bit_depth_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_geometry_2d_bit_depth_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_log2_max_atlas_frame_order_cnt_lsb_minus4);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_max_dec_atlas_frame_buffering_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_long_term_ref_atlas_frames_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_num_ref_atlas_frame_lists_in_asps);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_use_eight_orientations_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extended_projection_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_max_number_projections_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_normal_axis_limits_quantization_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_normal_axis_max_delta_value_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_patch_precedence_order_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_log2_patch_packing_block_size);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_patch_size_quantizer_present_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_map_count_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_pixel_deinterleaving_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_raw_patch_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_eom_patch_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_eom_fix_bit_count_minus1);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_auxiliary_video_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_plr_enabled_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_vui_parameters_present_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_present_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_vpcc_extension_present_flag);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_7bits);
  FVV_DECLARE_SCALAR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_data_flag);

  FVV_DECLARE_1D_STATIC_ARR_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, asps_map_pixel_deinterleaving_flag, 0x1 << FVV_BIT_ASPS_MAP_COUNT_MINUS1);

  FVV_DECLARE_OBJ_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, rls, fvv_ref_list_struct_t);
  FVV_DECLARE_OBJ_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, api, fvv_asps_plr_information_t);
  FVV_DECLARE_OBJ_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, vp, fvv_vui_parameters_t);
  FVV_DECLARE_OBJ_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, ave, fvv_asps_vpcc_extension_t);
  FVV_DECLARE_OBJ_SETTER_PTR(fvv_atlas_sequence_parameter_set_rbsp_t, rtb, fvv_rbsp_trailing_bits_t);
};
fvv_ret_t fvv_atlas_sequence_parameter_set_rbsp_init(
    fvv_atlas_sequence_parameter_set_rbsp_t *self,
    fvv_bitstream_t                         *data);
fvv_ret_t fvv_atlas_sequence_parameter_set_rbsp_destroy(
    fvv_atlas_sequence_parameter_set_rbsp_t *self);
fvv_ret_t fvv_atlas_sequence_parameter_set_rbsp_pack(
    fvv_atlas_sequence_parameter_set_rbsp_t *self);
fvv_ret_t fvv_atlas_sequence_parameter_set_rbsp_copy_from(
    fvv_atlas_sequence_parameter_set_rbsp_t *self,
    fvv_atlas_sequence_parameter_set_rbsp_t *other);

FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_atlas_sequence_parameter_set_id);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_frame_width);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_frame_height);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_geometry_3d_bit_depth_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_geometry_2d_bit_depth_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_log2_max_atlas_frame_order_cnt_lsb_minus4);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_max_dec_atlas_frame_buffering_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_long_term_ref_atlas_frames_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_num_ref_atlas_frame_lists_in_asps);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_use_eight_orientations_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extended_projection_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_max_number_projections_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_normal_axis_limits_quantization_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_normal_axis_max_delta_value_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_patch_precedence_order_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_log2_patch_packing_block_size);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_patch_size_quantizer_present_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_map_count_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_pixel_deinterleaving_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_raw_patch_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_eom_patch_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_eom_fix_bit_count_minus1);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_auxiliary_video_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_plr_enabled_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_vui_parameters_present_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_present_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_vpcc_extension_present_flag);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_7bits);
FVV_DECLARE_SCALAR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_extension_data_flag);

FVV_DECLARE_1D_STATIC_ARR_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, asps_map_pixel_deinterleaving_flag, 0x1 << FVV_BIT_ASPS_MAP_COUNT_MINUS1);

FVV_DECLARE_OBJ_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, rls, fvv_ref_list_struct_t);
FVV_DECLARE_OBJ_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, api, fvv_asps_plr_information_t);
FVV_DECLARE_OBJ_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, vp, fvv_vui_parameters_t);
FVV_DECLARE_OBJ_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, ave, fvv_asps_vpcc_extension_t);
FVV_DECLARE_OBJ_SETTER(fvv_atlas_sequence_parameter_set_rbsp_t, rtb, fvv_rbsp_trailing_bits_t);

#endif // FVV_SYNTAX_ATLAS_SEQUENCE_PARAMETER_SET_RBSP_H